### ISSUE TITLE
GibhubLernening And Development Environment

### ISSUE THREAD

**Issue by zhaofeng-shu33** [Leidenschaft/Deutsch-Lernen#3]
Two days ago, I received your Wechat message that you were somehow busying for your business. I understand you but forget to reply. Now I applogize for such neglect.
    One of my pc has some problem, and I have to edit **.xml with Visual Studio.  VS has grammar check against dtd and is not a bad choice.
    If you have time, you can continue contributing to this project as you like.
    Thanks.

**Comment by xiaokai0325** [comment]
It doesn't matter. I understand that you are busy,too. I forget to message you that i am free after yesterday. I want to make some contribute to the project, but it sometimes maybe a little difficult for me, as i don't know how to begin. What if i were also in Tinghua University!  But it is also okay because i can learn many things on the Internet. Anyway, i'm going to start now^&^
